name: CMake Windows

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        arch: [x64, arm64]
        include:
          - arch: x64
            vcpkg_triplet: x64-windows
            cmake_platform: x64
            runner: windows-latest

          - arch: arm64
            vcpkg_triplet: arm64-windows
            cmake_platform: ARM64
            runner: windows-11-arm

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
#Vcpkg runner
      - name: Run vcpkg for ${{ matrix.arch }}
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgArguments: >
            getopt:${{ matrix.vcpkg_triplet }}
            libiconv:${{ matrix.vcpkg_triplet }}
            libpng:${{ matrix.vcpkg_triplet }}
          vcpkgGitCommitId: '305c06bd4dee21e23dcf142c85c657a993f7aa1a'

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build-${{ matrix.arch }}

      - name: Configure CMake for ${{ matrix.arch }}
        shell: bash
        working-directory: ${{runner.workspace}}/build-${{ matrix.arch }}
        run: |
          cmake $GITHUB_WORKSPACE \
            -A ${{ matrix.cmake_platform }} \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }} \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            -DWITH_TESTS=yes

      - name: Build for ${{ matrix.arch }}
        working-directory: ${{runner.workspace}}/build-${{ matrix.arch }}
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test for ${{ matrix.arch }}
        working-directory: ${{runner.workspace}}/build-${{ matrix.arch }}
        shell: bash
        run: ctest -C $BUILD_TYPE --output-on-failure