name: CMake Windows

on:
  - push
  - pull_request

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x64
            vcpkg_triplet: x64-windows
            cmake_platform: x64
            runner: windows-latest

          - arch: arm64
            vcpkg_triplet: arm64-windows
            cmake_platform: ARM64
            runner: windows-11-arm

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run vcpkg for ${{ matrix.arch }}
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgArguments: >
            getopt:${{ matrix.vcpkg_triplet }}
            libiconv:${{ matrix.vcpkg_triplet }}
            libpng:${{ matrix.vcpkg_triplet }}
            zlib:${{ matrix.vcpkg_triplet }}
          vcpkgGitCommitId: 'cd61e1e26a038e82d6550a3ebbe0fbbfe7da78e3'

      - name: Show vcpkg environment
        shell: bash
        run: |
          echo "VCPKG_ROOT=$VCPKG_ROOT"
          "$VCPKG_ROOT/vcpkg" list

      - name: Create Build Environment
        run: cmake -E make_directory ${{ runner.workspace }}/build-${{ matrix.arch }}

      - name: Configure CMake for ${{ matrix.arch }}
        shell: bash
        working-directory: ${{ runner.workspace }}/build-${{ matrix.arch }}
        run: |
          cmake "$GITHUB_WORKSPACE" \
            -A ${{ matrix.cmake_platform }} \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }} \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            -DWITH_TESTS=yes

      - name: Build for ${{ matrix.arch }}
        shell: bash
        working-directory: ${{ runner.workspace }}/build-${{ matrix.arch }}
        run: |
          cmake --build . --config $BUILD_TYPE

      - name: Test for ${{ matrix.arch }}
        shell: bash
        working-directory: ${{ runner.workspace }}/build-${{ matrix.arch }}
        run: |
          ctest -C $BUILD_TYPE --output-on-failure